### PR TITLE
removed illegal statment before IffFormLoad for testing

### PR DESCRIPTION
**Pull request by marc365**
if you check the files that were removed in the [debug commit](https://github.com/AmosFactory/AmosProfessional/commit/195e375539fd9d4bf8ae596138b180cc59efb1f2) and the temp/Docs files you will see multiple references to a bug in the anim playback and actually an [anim file](https://github.com/AmosFactory/AmosProfessional/blob/5ea5aa1b4ee77726c54558b8f3feefcd40c9549e/Bug.Anim) in the original archive, I think the [debuging](https://github.com/AmosFactory/AmosProfessional/commit/195e375539fd9d4bf8ae596138b180cc59efb1f2) was looking at this functionality, and the illegal statement is there at this point working with Iff data.

### CODE REVIEW

**Comment by marc365** [comment]
I suppose looking at that anim file is a good idea and try playing it with the new binary against the old.

from this we can't assertain that the original bug in the anim system is fixed with the code present and that it would still cause the bug without this illegal call - if it is an unfixed bug at this point that can be confirmed, and it should be handled more gracefully.

**Comment by marc365** [comment]
Leave a c;	bruceuncle
;	14/10/2013
;
; The V2.00 binary does not have this, but the V2.00
; source does!.

**Comment by marc365** [comment]
"we can't assertain that the original bug in the anim system is fixed" - possibly not true, as Bruce's statement seems to indicate that a binary compare shows that instruction up?

**Comment by marc365** [comment]
ok, the bug doesn't show up with the animation, both version play it successfully - I was assuming amos would bomb out (I tested by adding illegal to the startup and it does crash!) so I'm wasting my time here but fortunatly it's a great anim - go take a look - load Bug.AMOS and then select Bug.Anim, I did't look before... next update I will look closer at where this would fire and if possible run something to do it.

**Comment by marc365** [comment]
searching the entire text highlights a number of illegal statements and in the music extension is:

; To produce your own extension, I suggest you copy and rename this
; file, and remove the used code. This way you will not forgive one line.
; Also keep in mind that you can perfectly call AMOS from within MONAM2,
; and set some ILLEGAL instructions where you want to debug. To flip back to
; MONAM2 display, just press AMIGA-A.

there are some commands used inside debug code, but it isn't commented out here - there were some files prepared with debug statements removed so I have to now check to see if these would be removed by that also. it also seems that my previous statement about debug code only being added inside compiler directives, but the cleanup code may have highlighted these - but those files are presented as is, not within a build, and no confirmation that it builds, and then no confirmation that it actually run code a perfectly as the original.

do you see how difficult this can become - unless we follow a process it is impossible - maybe after just relooking at the commented out debug code that Bruce did I'll understand more. 

@Michael, you mentioned having the know-how to put together some git guidelines, If possible we hold up on this and get a process for integration - I'll give it some thought as well.

**Comment by SamuraiCrow** [comment]
Perhaps it should be noted that the illegal trap vector is used by debugger software to set break points.  Some assemblers use the bkpt opcode as an alias for it.

 That being the case, illegal trap vector invocations should be replaced globally with a macro that can be disabled in a release build.

**Comment by marc365** [comment]
thanks yes that may solve not knowing where they are, I'm going to rebuild the [debug versions](https://github.com/AmosFactory/AmosProfessional/issues/17) and run monam2. also maybe write it out before I post comments next time.

**Pull request closed without merging**
