### PR TITLE
merged BruceUncles menu contribution

### PR DESCRIPTION
**Pull request by marc365**
all the configuration files are now built without devpac compatibility mode. This was a good opportunity to test, and it is noted that the assembled binaries are exactly the same when assembled without the -devpac option. the +editor_config.s is upgraded to have BruceUncles contribution, and I've built the config files. also took an opportunity to clean up the build and remove the completed files.

### CODE REVIEW

**Comment by marc365** [comment]
the menu data is merged with the main file - check it out it fits perfectly
devpac still works and being maintained, no reason to pull it yet, it's the -devpac compatibility mode that is being removed, there are only small issues, and i've done some of them - everything builds perfectly still - no commit will break that.

**Comment by marc365** [comment]
click the "Load the Diff" button for +editor_config.s and you will see it.

**Comment by mness1978** [comment]
I'm only showing 4 commits on this branch, all from a day ago.  marc365, are you sure you pushed your changes mentioned in issue #35?

**Comment by marc365** [comment]
this link may be better - it snaps open to the +editor_config.s where the changes are:

https://github.com/AmosFactory/AmosProfessional/pull/32/commits/463bbc2e5ca66133c723f844140be9860f8ce178#diff-50c479ec03ae39fa9b0432908c51b976

**Comment by marc365** [comment]
> I'm only showing 4 commits on this branch

I think I understand better now, I did add a few files on each commit, so the removal and pasteing in happened on the same commit, so this all becomes more difficult to read, thanks for showing and doing it, i think when i branch i can make smaller commits with a better title to follow it better, it isn't the easiest reviewing it on the web, and i see what you mean, do rush dude - just say if you need some more pointers to the bits - i'll make it better next time - finishing the vasm with -devpac compatibility mode and making sure it still builds with genam, so i will make many more steps shown in the commits... thanks.

**Comment by marc365** [comment]
you've also got me thinking now - I've wondered in the past if these menu's were created with a tool as there was no source for them and they are bascially data files, and I just had the idea that maybe the data is actualy a menu bank made using the "Menu To Bank" command, and then split up - I didn't check this before, it would be interesting to know, but not going to promise when i do that ;-)

**Pull request merged**
